apiVersion: apps/v1
kind: Deployment
metadata:
  name: boobtree
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: boobtree
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: boobtree
    spec:
      containers:
      - env:
        - name: MONGODB
          valueFrom:
            configMapKeyRef:
              key: MONGODB
              name: boobtree-config-4cyc
        image: gcr.io/prefab-conquest-186122/boobtree@sha256:a6af368286a1ed56e447da6dcff26c7377a2549d7cf5729597dd527bb19c5db6
        imagePullPolicy: IfNotPresent
        name: boobtree-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
